build:
  image: registry.local/buildimage-nodejs:latest
  commands:
    - tools/gen-service-defs.sh

publish:
  docker:
    image: plugins/drone-docker
    repo: registry.local/test-server
    tag:
      - latest
      - $$BRANCH
      - $$BRANCH-$$COMMIT-$$BUILD_NUMBER
  s3:
    image: plugins/drone-s3
    acl: public-read
    region: eu-west-1
    bucket: build-artifacts
    access_key: $$S3_ACCESS_KEY
    secret_key: $$S3_SECRET_KEY
    source: service-defs/
    target: test-server/
    recursive: true
